apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cardcraft-backend
  labels:
    cloud.googleapis.com/location: us-central1
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '0'
        autoscaling.knative.dev/maxScale: '10'
        run.googleapis.com/cpu-throttling: 'true'
        run.googleapis.com/startup-cpu-boost: 'false'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 60
      serviceAccountName: PROJECT_NUMBER-compute@developer.gserviceaccount.com
      containers:
      - image: us-central1-docker.pkg.dev/PROJECT_ID/cardcraft/backend:latest
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: GOOGLE_API_KEY
          valueFrom:
            secretKeyRef:
              key: latest
              name: google-api-key

        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: latest
              name: google-client-id
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: latest
              name: google-client-secret
        - name: TOKEN_ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              key: latest
              name: token-encryption-key
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              key: latest
              name: jwt-secret
        - name: STRIPE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: latest
              name: stripe-secret-key
        - name: STRIPE_WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              key: latest
              name: stripe-webhook-secret
        - name: GOOGLE_REDIRECT_URI
          value: https://PROJECT_ID.web.app/oauth-callback.html
        - name: ALLOWED_ORIGINS
          value: https://PROJECT_ID.web.app
        - name: GOOGLE_CLOUD_PROJECT
          value: PROJECT_ID
        resources:
          limits:
            cpu: '1'
            memory: 256Mi
        startupProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 0
          timeoutSeconds: 1
          periodSeconds: 3
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 0
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3
  traffic:
  - percent: 100
    latestRevision: true
